# Generated by Django 5.0.3 on 2024-03-25 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('duration', models.DurationField()),
                ('progress', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='usertest.course'),
        ),
    ]
