# Generated by Django 5.0.3 on 2024-03-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertest', '0002_course_video_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.URLField(),
        ),
    ]
