# Generated by Django 5.0.3 on 2024-03-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertest', '0007_assessment_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='user_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
