# Generated by Django 5.0.3 on 2024-03-30 13:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertest', '0010_alter_assessment_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='users_completed',
            field=models.ManyToManyField(blank=True, related_name='completed_assessments', to=settings.AUTH_USER_MODEL),
        ),
    ]
