# Generated by Django 5.0.3 on 2024-04-06 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertest', '0013_remove_course_thumbnail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='completed',
        ),
        migrations.CreateModel(
            name='AssessmentCompleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_submitted', models.TimeField()),
                ('date_submitted', models.DateField()),
                ('percentage_secured', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mark', models.PositiveIntegerField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usertest.assessment')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usertest.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
