# Generated by Django 5.0.3 on 2024-04-06 17:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertest', '0014_remove_assessment_completed_assessmentcompleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentcompleted',
            name='time_submitted',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
