# Generated by Django 5.0.3 on 2024-04-06 18:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertest', '0015_alter_assessmentcompleted_time_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentcompleted',
            name='date_submitted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
