# Generated by Django 5.0.3 on 2024-04-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertest', '0016_alter_assessmentcompleted_date_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentcompleted',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
